### PR TITLE
Add Latitude and Longitude to telemetry widget

### PR DESCRIPTION
**Pull request by guiseco**
Added latitude and longitude data to the telemetry widget.

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@guiseco thanks for the pr!

**Comment by guiseco** [comment]
I wish to put a onclick listener on both textviews to copy values in clipboard using google format like this: "-50.00000, 50.0000". But i don't know where. Could you give me a advice ?

**Comment by ne0fhyk** [comment]
@guiseco I want ahead and added that functionality in commit a94190326d55ed166306c8be7fe23ab49fdac465

**Comment by guiseco** [comment]
Veeery nice !!! Thank you !!!!

**Pull request merged**
