### PR TITLE
Offline map support integration

### PR DESCRIPTION
**Pull request by ne0fhyk**
This PR adds support for offline maps download, and integration within Tower.

In order to use this feature, a mapbox account is required to get access to the map tiles:

- Navigate to `Settings` -> `User Interface`, and select `google map` as map provider.
select_maps_providers

- Then navigate to the google map preferences by selecting `Map Provider Preferences`.
- In the preferences screen, select `mapbox` as the tile provider.
select_tile_provider

- Then enter a valid account's mapbox `id` and `access token`.
mapbox_id_preference

mapbox_access_token_preference

Once this setup is complete, offline maps can be downloaded either from the `Map Provider Preferences` screen, or (if enabled) from the overflow menu (3 dots in the action bar) in the maps screens:

download_map_menu_option

map_area_selection

map_download_screen

### CODE REVIEW

**Comment by hsteinhaus** [comment]
Very nice idea, but please add a paste button for the mapbox API token :)

**Comment by ne0fhyk** [comment]
@hsteinhaus since it's a input field, you can long click on it, and the `paste` option should come up!

**Comment by hsteinhaus** [comment]
Unfortunately not working here (Android 4.4.4/CM11 on Amazon Tate). Other apps bring up the paste option on long press, as expected (e.g. Chrome), but not Tower. I tested the latest available beta.

**Comment by ne0fhyk** [comment]
It may be an issue with your device. The paste option comes up on mine as long as something is already copied in the clipboard.

screenshot_2015-10-01-15-55-23

**Comment by smocksam** [comment]
Can you post a pic of on the map box site showing what needs to be copied there?

And an example of how it looks plugged into the app?


There is an api and a token that I believe is specific to each map you make?

I'm not sure which info to put in and what format or should be in?

Thanks

**Pull request merged**
