### PR TITLE
Update Chinese(simplified) translation

### PR DESCRIPTION
**Pull request by SkiTiSu**
Thanks.

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@SkiTiSu thanks for the updated translation!

However, the pull request should be done against the `develop` branch.

**Comment by ne0fhyk** [comment]
@SkiTiSu additionally, there seem to be an issue caused by the lack of the closing tag on line 430.

**Comment by SkiTiSu** [comment]
I'm sorry, I forgot a ">".

**Comment by ne0fhyk** [comment]
@SkiTiSu can you also reopen this pull request against the `develop` branch instead.

**Comment by SkiTiSu** [comment]
@ne0fhyk OK. I'm sorry.

**Pull request closed without merging**
