### PR TITLE
Added support to video streaming using a UVC DEVICE + Brazilian Portuguese

### PR DESCRIPTION
**Pull request by guiseco**
Beta Version

p_20151108_202530
p_20151107_202804
p_20151107_210451
p_20151107_202919
p_20151107_202753

https://goo.gl/photos/3vjUMi8ZzV9wgJN67

### CODE REVIEW

**Comment by guiseco** [comment]
d945f562-8927-11e5-9616-4199540da146

**Comment by guiseco** [comment]
d945f562-8927-11e5-9616-4199540da146

**Comment by ne0fhyk** [comment]
@guiseco still working on it?

**Comment by kudykam** [comment]
Are you planning to add support for EasyCap devices as well (UTV007 chipset)?

**Pull request closed without merging**
