### PR TITLE
Add BaiduMap v4.0.0 support - For merging

### PR DESCRIPTION
**Pull request by droneboost**
@ne0fhyk

I've  squashed commit histories in this PR, would you please check and approve merge?

Thanks.

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@droneboost looks good to go!

**Comment by droneboost** [comment]
@ne0fhyk, thanks for merging.

**Comment by Tanson** [comment]
我还是用中文向飞鱼的作者致敬吧，一直在用。谢谢。

**Comment by Linjieqiang** [comment]
@Tanson Thanks.Also thanks @droneboost code for baidu map.

**Comment by droneboost** [comment]
@Linjieqiang, Thanks!    We are looking forward to see your PR with more new feature for CN maps.  Let's  make Tower a better GCS App together.

**Comment by ne0fhyk** [comment]
@droneboost I'm preparing to release the first beta for version 4.0. How do I go about updating the  baidu map developer key?

**Comment by droneboost** [comment]
@ne0fhyk , do you have a Baidu developer account? If don't have, please register an account on following links:

https://passport.baidu.com/v2/?reg&tpl=newdev&u=http://developer.baidu.com/

**Comment by ne0fhyk** [comment]
@droneboost I'm unable to register for an account since it requires a chinese mobile phone number. Any suggestions?

**Comment by droneboost** [comment]
@ne0fhyk , seems Chinese mobile phone number is a prerequisite of BD developer account,  for the time being, I think I can apply a  map API key for you for testing, if you share your android SDK sha1 signature to me, please check this page: http://lbsyun.baidu.com/index.php?title=androidsdk/guide/key

**Comment by ne0fhyk** [comment]
@droneboost sounds good. Can you send me your email address, so I can email you the sha1 fingerprint. You can find my email address on my github profile. I'm unable to find your email on github though.

In addition, am I able to release the app with the map API key you will send?

**Comment by droneboost** [comment]
@ne0fhyk , my email : droneboost@gmail.com, I've sent you an email.

> In addition, am I able to release the app with the map API key you will send?
Sure! Before you are able to get your own Baidu developer account, I'm glad to maintain the baidu map API key for Tower.

**Pull request merged**
