### PR TITLE
Update the app to show in full screen

### PR DESCRIPTION
**Pull request by preet90**

### CODE REVIEW

**Comment by billbonney** [comment]
I won't be merging this change. HID guidelines for apps is not remove status bar. Since it would require users to task away to check the time and connection status.

**Comment by gmorph** [comment]
The problem is that in landscape mode the right hand popup HUD display doesn't fit completely on the screen.  With the app full screen it does.  Plus the full screen gives more app real-estate.
Bill would you be open to it being a configuration option that users could select?

**Comment by billbonney** [comment]
MAybe on Smaller screens, but I am not seeing it. If you want to make it configurable, that's OK.
[
screenshot_20171112-190157
](url)

**Comment by gmorph** [comment]
Thanks Bill.  We will look into making it an option.
Thanks, Grant.

**Pull request closed without merging**
