### PR TITLE
Set "min step height" to ZERO instead of MIN_ALTITUDE

### PR DESCRIPTION
**Pull request by guiseco**
IF MIN_ALTITUDE was set to a value greater than ZERO we cannot set Step height below that value.

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@guiseco what about the case where the drone take off at a altitude higher than the structure it's planning to scan. In that case setting step height to a negative value is required to complete the scan.

**Comment by guiseco** [comment]
@ne0fhyk Let me see if i understand this correctly.

Ex: Structure Scan
Start Altitude = 50m
Step Height = -5m (negative)
Number of Steps = 5

In this way the drone start at 50m and go down until 25m. is it ?

**Comment by ne0fhyk** [comment]
@guiseco yep

**Comment by guiseco** [comment]
@ne0fhyk This is a new feature, right ? I mean, today we can just increment the altitude.

**Comment by ne0fhyk** [comment]
@guiseco no, it's been there since v3.2.0. Under `Settings` -> `Advanced Settings`, there's an option to update the min/max/default altitude. 
Most of the mission items, including the structure scanner, take their altitude bounds from these preferences. Hence if you set the min altitude value in the preferences to a negative value, the structure scanner mission item will let you set the step height to a negative value as well.

When we're building SiteScan on Android, we thought about having a structure scanner mission follow the path i described above. The copter would go to the top of structure, and scan it by 'stepping down', instead of going to the base, and scan it by 'stepping up'.

**Comment by guiseco** [comment]
@ne0fhyk Sorry for my mistake ! I Will close this pr !!!

**Pull request closed without merging**
