### PR TITLE
Added vehicle specific icons

### PR DESCRIPTION
**Pull request by preet90**

### CODE REVIEW

**Comment by gmorph** [comment]
LGTM.  I helped preet90 with his environment setup but he has done the coding and testing.  Hopefully this will be the first of a few PRs coming in.

**Comment by squilter** [comment]
The icons that are missing are sub and antennatracker. Obviously those are kinda rare, so maybe not worth the effort, but I think it might be better to at least show a dot or something in their place.

**Comment by gmorph** [comment]
Yeah I didn't think people would be use Tower for either of those.  We do show an unavailable icon when we don't know what vehicle type it is. We can have a look.

**Comment by billbonney** [comment]
As commented in the other PR, it should be the old 'arrow' icon. And I think it should be optional for new icons or the old arrow.

**Pull request merged**
